# ==========================================
# CONFIGURACIÓN DEL SERVIDOR
# ==========================================
server.base_uri=http://0.0.0.0:8081/
database.persistence_unit.name=SimServerPU
# ==========================================
# CONFIGURACIÓN DE LA SIMULACIÓN
# ==========================================
simulation.ticks_to_run=100
simulation.initial_occupancy=0.35
simulation.food_probability=1.0
# ==========================================
# CONFIGURACIÓN DE CRIATURAS
# ==========================================
# Estática
creature.static.names=perezoso,koala,adrian
creature.static.colors=green,darkgreen,violet
creature.static.starvation_thresholds=5,6,10
# Móvil
creature.mobile.names=gato,perro,juanlu
creature.mobile.colors=red,darkred,cyan
creature.mobile.starvation_thresholds=5,4,7
creature.mobile.move_probabilities=0.5,0.6,0.4
# Conejo estático
creature.static_rabbit.names=conejo,raton,unai
creature.static_rabbit.colors=blue,darkblue,yellow
creature.static_rabbit.starvation_thresholds=5,3,8
creature.static_rabbit.multiply_probabilities=0.2,0.3,0.1