# ==========================================
# CONFIGURACIÓN DEL SERVIDOR
# ==========================================
server.base_uri=http://0.0.0.0:8081/
database.persistence_unit.name=SimServerPU
# ==========================================
# CONFIGURACIÓN DE LA SIMULACIÓN
# ==========================================
simulation.ticks_to_run=100
simulation.initial_occupancy=0.3
simulation.food_probability=0.2
# ==========================================
# CONFIGURACIÓN DE CRIATURAS
# ==========================================
# Estática
creature.static.names=panda
creature.static.starvation_thresholds=10
# Móvil
creature.mobile.names=delfin
creature.mobile.starvation_thresholds=4
creature.mobile.move_probabilities=0.8
# Conejo estático
creature.static_rabbit.names=pandolin
creature.static_rabbit.starvation_thresholds=2
creature.static_rabbit.multiply_probabilities=0.2